In [1]:
import psycopg2
import pandas as pd

In [2]:
conn = psycopg2.connect(
   database="d65103c5a2kbgs", 
    user='u16ifm924gr2m8', 
    password='pe4029f0ba1fbaafd034f4dbf17f703bf9a5d6c8420f07719f5db4054c9d4da40', 
    host='c1gvrf2q90nbcq.cluster-czrs8kj4isg7.us-east-1.rds.amazonaws.com', 
    port = '5432'
    
)
cursor = conn.cursor()

In [3]:
sql = '''SELECT * from modified_label'''
data = pd.read_sql_query(sql, conn)

/var/folders/f5/vn3dt39d3hl4z6fvrlqn3s300000gp/T/ipykernel_2451/913544206.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  data = pd.read_sql_query(sql, conn)

In [4]:
len(data)

3723

In [5]:
data

,uuid,user_id,docid,source,summary,model,benchmark_dataset_name,origin,nonfactual_span,error_type,mistake_severity,inference_likelihood,inference_knowledge,inference_severity,attempt_number
0,56d81429-97f5-4dac-8eec-aed5f430d506,4vQZBQ,LLM-AggreFact:DqeLab1jnlXl51TV6g3fEIphiWL9btS0...,"Title: late rally for doc adams, a jeter befor...","""The New York Times"" published an article on A...",unknown,Wice,Wice,NaN,NaN,NaN,NaN,NaN,NaN,1
1,a5b223ca-7006-406a-96b7-900447c71fc4,USzArg,LLM-AggreFact:qw1pBWz5ynI76U121ehgtFXQXzIGP5lw...,Speaker 1: motion carries.\nSpeaker 0: thank y...,The document discusses the importance of oppos...,unknown,TofuEval-MeetB,TofuEval-MeetB,aims to repeal gas and vehicle taxes that fund...,highlight-inference,NaN,obvious,common,low_consequence,1
2,8742b6b1-a92e-4aec-920d-673e779ddc8c,USzArg,LLM-AggreFact:q56mHW6cfwgyKnrPD79U1HaTv2YaBZuP...,If there''s one thing that hurts more than the...,He can now continue his journey to his final d...,unknown,RAGTruth,RAGTruth,NaN,NaN,NaN,NaN,NaN,NaN,1
3,91786a5f-f376-41e9-8e93-038c9ef8fb74,YtYC5w,LLM-AggreFact:Q93Y9kC2QHHtQbdTNTouc7bXcTFWJCzp...,Title: theresa serber malkiel | jewish women''...,Her parents were Russian Jewish immigrants and...,unknown,Wice,Wice,Russian,highlight-inference,NaN,likely,common,moderate_consequence,1
4,3e847b65-9b87-41bf-b4ef-488a0271ebc4,USzArg,LLM-AggreFact:kvgYpbrK7d3F0wr6E4e9bznPh7DWgVBl...,We want our killers to be kind.\nTo walk into ...,"However, the NFL and the Patriots handled the ...",unknown,RAGTruth,RAGTruth,defend him as a good person,highlight-inference,NaN,obvious,common,low_consequence,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3718,fde6b37f-7c95-48d7-b2e3-332c6baaf866,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,his,highlight-inference,None,likely,somewhat_common,moderate_consequence,1
3719,9dc29b73-6126-460f-a890-d00de9d55958,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,his,highlight-inference,None,likely,somewhat_common,moderate_consequence,1
3720,95e33825-5f8e-4ae0-a629-7a431074170d,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,several people in the audience turned to see w...,highlight-inference,None,not_likely,common,moderate_consequence,1
3721,d6ba990e-647e-491e-8eee-fc14d64e9c41,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,him,highlight-inference,None,likely,somewhat_common,moderate_consequence,1
3722,6812a037-7c1f-418c-86c8-abb058204ba5,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,"the rest of the day went on, with him barely k...",highlight-somewhat_mistake,None,not_likely,common,moderate_consequence,1

In [6]:
spans_docid = list(data[data['docid'] == 'ACIBENCH-D2N098:llama70b-ul2']['nonfactual_span'])
{span: spans_docid.count(span) for span in set(spans_docid)}

{'conducted a physical examination': 1, None: 3, 'visited a doctor': 1}

In [7]:
data.to_csv('/Users/ramprasad.sa/hallucinations_annotations_trial/annotated_data/database_dump_hallu_trial_Feb_8_2025.csv')

In [8]:
data

,uuid,user_id,docid,source,summary,model,benchmark_dataset_name,origin,nonfactual_span,error_type,mistake_severity,inference_likelihood,inference_knowledge,inference_severity,attempt_number
0,56d81429-97f5-4dac-8eec-aed5f430d506,4vQZBQ,LLM-AggreFact:DqeLab1jnlXl51TV6g3fEIphiWL9btS0...,"Title: late rally for doc adams, a jeter befor...","""The New York Times"" published an article on A...",unknown,Wice,Wice,NaN,NaN,NaN,NaN,NaN,NaN,1
1,a5b223ca-7006-406a-96b7-900447c71fc4,USzArg,LLM-AggreFact:qw1pBWz5ynI76U121ehgtFXQXzIGP5lw...,Speaker 1: motion carries.\nSpeaker 0: thank y...,The document discusses the importance of oppos...,unknown,TofuEval-MeetB,TofuEval-MeetB,aims to repeal gas and vehicle taxes that fund...,highlight-inference,NaN,obvious,common,low_consequence,1
2,8742b6b1-a92e-4aec-920d-673e779ddc8c,USzArg,LLM-AggreFact:q56mHW6cfwgyKnrPD79U1HaTv2YaBZuP...,If there''s one thing that hurts more than the...,He can now continue his journey to his final d...,unknown,RAGTruth,RAGTruth,NaN,NaN,NaN,NaN,NaN,NaN,1
3,91786a5f-f376-41e9-8e93-038c9ef8fb74,YtYC5w,LLM-AggreFact:Q93Y9kC2QHHtQbdTNTouc7bXcTFWJCzp...,Title: theresa serber malkiel | jewish women''...,Her parents were Russian Jewish immigrants and...,unknown,Wice,Wice,Russian,highlight-inference,NaN,likely,common,moderate_consequence,1
4,3e847b65-9b87-41bf-b4ef-488a0271ebc4,USzArg,LLM-AggreFact:kvgYpbrK7d3F0wr6E4e9bznPh7DWgVBl...,We want our killers to be kind.\nTo walk into ...,"However, the NFL and the Patriots handled the ...",unknown,RAGTruth,RAGTruth,defend him as a good person,highlight-inference,NaN,obvious,common,low_consequence,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3718,fde6b37f-7c95-48d7-b2e3-332c6baaf866,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,his,highlight-inference,None,likely,somewhat_common,moderate_consequence,1
3719,9dc29b73-6126-460f-a890-d00de9d55958,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,his,highlight-inference,None,likely,somewhat_common,moderate_consequence,1
3720,95e33825-5f8e-4ae0-a629-7a431074170d,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,several people in the audience turned to see w...,highlight-inference,None,not_likely,common,moderate_consequence,1
3721,d6ba990e-647e-491e-8eee-fc14d64e9c41,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,him,highlight-inference,None,likely,somewhat_common,moderate_consequence,1
3722,6812a037-7c1f-418c-86c8-abb058204ba5,USzArg,REDDIT-37:falcon7b-ul2,Context: i've recently come down with a pretty...,"feeling a little under the weather, a friend a...",falcon7b,genaudit,REDDIT,"the rest of the day went on, with him barely k...",highlight-somewhat_mistake,None,not_likely,common,moderate_consequence,1

NameError: name 'doc' is not defined